Add SSL support and some other features
The list of things is
* Remove redundancy in config manifest.
* Add support for SSL.
* Add ssl certificate, ssl key and motd file options.
* Fix requires.
* Rewrite the init script.

diff --git a/templates/unreal.erb b/templates/unreal.erb
--- a/templates/unreal.erb
+++ b/templates/unreal.erb
@@ -1,94 +1,139 @@
-#!/bin/sh
-
-# unreal Start/stop the Unreal IRC server.
-
+#! /bin/sh
 ### BEGIN INIT INFO
 # Provides:          ircd
-# Required-Start:    $syslog
-# Required-Stop:     $syslog
-# Should-Start:      $local_fs $network $named
-# Should-Stop:       $local_fs $network $named
+# Required-Start:    $remote_fs $network $syslog
+# Required-Stop:     $remote_fs $network $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: UnrealIRCd daemon init.d script
 # Description:       Use to manage the UnrealIRCd daemon.
 ### END INIT INFO
 
-PATH=/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+DESC="Unreal (<%= scope.lookupvar('unrealirc::servername') %>)"
+NAME=unreal
 DAEMON=<%= scope.lookupvar('unrealirc::install_path') %>/src/ircd
-NAME="UnrealIRCd (<%= scope.lookupvar('unrealirc::servername') %>)"
+DAEMON_ARGS=""
 USER=<%= scope.lookupvar('unrealirc::user') %>
 GROUP=<%= scope.lookupvar('unrealirc::group') %>
 PIDFILE=<%= scope.lookupvar('unrealirc::pidfile') %>
+SCRIPTNAME=/etc/init.d/$NAME
 
-test -f $DAEMON || exit 0
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
 
-set -e
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
+. /lib/lsb/init-functions
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon --start --quiet -c $USER:$GROUP --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+		|| return 1
+	start-stop-daemon --start --quiet -c $USER:$GROUP --pidfile $PIDFILE --background --exec $DAEMON -- \
+		$DAEMON_ARGS > /dev/null\
+		|| return 2
+}
+
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	# Wait for children to finish too if this is a daemon that forks
+	# and if the daemon is only ever run from this initscript.
+	# If the above conditions are not satisfied then add some other code
+	# that waits for the process to drop all resources that could be
+	# needed by services started subsequently.  A last resort is to
+	# sleep for some time.
+	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	[ "$?" = 2 ] && return 2
+	# Many daemons don't delete their pidfiles when they exit.
+	rm -f $PIDFILE
+	return "$RETVAL"
+}
+
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+	#
+	# If the daemon can reload its configuration without
+	# restarting (for example, when it is sent a SIGHUP),
+	# then implement that here.
+	#
+	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+	return 0
+}
 
 case "$1" in
   start)
-        PID=`ps -e | grep ircd | awk '{ print $1 }'`
-        if [ -z $PID ] ; then
-          echo -n "Starting $NAME with pid $PIDFILE"
-          start-stop-daemon --oknodo --start --quiet --exec $DAEMON \
-                --user $USER -c $USER --pidfile "$PIDFILE" > /dev/null
-          echo "."
-        else
-          echo "ERROR: $NAME is already running on pid $PID..."
-          exit 1
-        fi
-
-        break
-        ;;
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
   stop)
-        if [ ! -r $PIDFILE ] ; then
-          echo "ERROR: $NAME is not running"
-          exit 1
-        fi
-        echo -n "Stopping $NAME"
-        start-stop-daemon --pidfile "$PIDFILE" --oknodo --stop --quiet \
-               --signal 15 --exec $DAEMON
-        rm $PIDFILE
-        echo "."
-        break
-        ;;
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
   status)
-        PID=`ps -e | grep ircd | awk '{ print $1 }'`
-        if [ -z $PID ] ; then
-          echo "$NAME is not running."
-        else
-          echo "$NAME is running on pid $PID..."
-        fi
-        break
-        ;;
-
-  rehash)
-        echo "Rehashing UnrealIRCd"
-        if [ ! -r $PIDFILE ] ; then
-          echo "ERROR: UnrealIRCd is not running"
-          exit 1
-        fi
-        kill -1 `cat $PIDFILE`
-        echo "."
-        break
-        ;;
-  restart|force-reload)
-        echo -n "Restarting $NAME"
-        if [ -f $PIDFILE ]; then
-          start-stop-daemon --stop --oknodo --quiet --pidfile "$PIDFILE" --signal 15 --exec $DAEMON
-          rm $PIDFILE
-          sleep 1
-        fi
-        start-stop-daemon --start --oknodo --quiet --user $USER -c $USER \
-              --pidfile "$PIDFILE" --exec $DAEMON > /dev/null
-        echo "."
-        break
-        ;;
+	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+	;;
+  reload)
+	log_daemon_msg "Reloading $DESC" "$NAME"
+	do_reload
+	log_end_msg $?
+	;;
+  restart)
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+		# Failed to stop
+		log_end_msg 1
+		;;
+	esac
+	;;
   *)
-        echo "Usage: $0 {start|stop|restart|rehash|force-reload}" >&2
-        exit 0
-        ;;
+	echo "Usage: $SCRIPTNAME {start|stop|restart|reload}" >&2
+	exit 3
+	;;
 esac
 
-exit 0
+:
